const cryptocurrencies = [
    { "name": "Bitcoin", "expectedReturn": 15, "risk": 4 },
    { "name": "Ethereum", "expectedReturn": 18, "risk": 5 },
    { "name": "Ripple", "expectedReturn": 12, "risk": 3 },
    { "name": "Litecoin", "expectedReturn": 10, "risk": 3 },
    { "name": "Cardano", "expectedReturn": 9, "risk": 2 },
    { "name": "Polkadot", "expectedReturn": 11, "risk": 3 },
    { "name": "Chainlink", "expectedReturn": 13, "risk": 4 },
    { "name": "Stellar", "expectedReturn": 8, "risk": 3 },
    { "name": "Dogecoin", "expectedReturn": 20, "risk": 5 },
    { "name": "Solana", "expectedReturn": 17, "risk": 5 },
    { "name": "Polygon", "expectedReturn": 14, "risk": 4 },
    { "name": "Binance Coin", "expectedReturn": 16, "risk": 4 },
    { "name": "Shiba Inu", "expectedReturn": 25, "risk": 6 },
    { "name": "VeChain", "expectedReturn": 9, "risk": 3 },
    { "name": "TRON", "expectedReturn": 10, "risk": 3 },
    { "name": "Tezos", "expectedReturn": 11, "risk": 4 },
    { "name": "Monero", "expectedReturn": 13, "risk": 4 },
    { "name": "Aave", "expectedReturn": 15, "risk": 5 },
    { "name": "Avalanche", "expectedReturn": 18, "risk": 5 },
    { "name": "Cosmos", "expectedReturn": 12, "risk": 3 },
    { "name": "Uniswap", "expectedReturn": 14, "risk": 4 },
    { "name": "Algorand", "expectedReturn": 10, "risk": 3 },
    { "name": "FTX Token", "expectedReturn": 11, "risk": 3 },
    { "name": "Theta", "expectedReturn": 13, "risk": 4 },
    { "name": "Elrond", "expectedReturn": 16, "risk": 5 },
    { "name": "NEO", "expectedReturn": 9, "risk": 3 },
    { "name": "Zcash", "expectedReturn": 10, "risk": 4 },
    { "name": "Dash", "expectedReturn": 8, "risk": 3 },
    { "name": "Hedera", "expectedReturn": 12, "risk": 3 },
    { "name": "Filecoin", "expectedReturn": 17, "risk": 5 },
    { "name": "IOTA", "expectedReturn": 8, "risk": 2 },
    { "name": "Harmony", "expectedReturn": 14, "risk": 4 },
    { "name": "Quant", "expectedReturn": 11, "risk": 3 },
    { "name": "SushiSwap", "expectedReturn": 13, "risk": 4 },
    { "name": "Yearn.Finance", "expectedReturn": 19, "risk": 5 },
    { "name": "Waves", "expectedReturn": 10, "risk": 3 },
    { "name": "PancakeSwap", "expectedReturn": 15, "risk": 4 },
    { "name": "Kusama", "expectedReturn": 16, "risk": 5 },
    { "name": "Arweave", "expectedReturn": 12, "risk": 4 },
    { "name": "Curve DAO", "expectedReturn": 14, "risk": 4 }
];

const commodities = [
    { "name": "Gold", "expectedReturn": 12, "risk": 1 },
    { "name": "Silver", "expectedReturn": 8, "risk": 2 },
    { "name": "Crude Oil", "expectedReturn": 15, "risk": 3 },
    { "name": "Natural Gas", "expectedReturn": 10, "risk": 4 },
    { "name": "Copper", "expectedReturn": 7, "risk": 2 },
    { "name": "Platinum", "expectedReturn": 9, "risk": 2 },
    { "name": "Corn", "expectedReturn": 5, "risk": 1 },
    { "name": "Wheat", "expectedReturn": 6, "risk": 1 },
    { "name": "Soybeans", "expectedReturn": 8, "risk": 2 },
    { "name": "Coffee", "expectedReturn": 10, "risk": 3 },
    { "name": "Cotton", "expectedReturn": 7, "risk": 2 },
    { "name": "Sugar", "expectedReturn": 5, "risk": 2 },
    { "name": "Palladium", "expectedReturn": 13, "risk": 3 },
    { "name": "Nickel", "expectedReturn": 11, "risk": 2 },
    { "name": "Zinc", "expectedReturn": 8, "risk": 2 },
    { "name": "Iron Ore", "expectedReturn": 9, "risk": 3 },
    { "name": "Aluminum", "expectedReturn": 6, "risk": 1 },
    { "name": "Cocoa", "expectedReturn": 4, "risk": 2 },
    { "name": "Rice", "expectedReturn": 3, "risk": 1 },
    { "name": "Rubber", "expectedReturn": 7, "risk": 2 },
    { "name": "Lead", "expectedReturn": 5, "risk": 2 },
    { "name": "Tin", "expectedReturn": 8, "risk": 2 },
    { "name": "Ethanol", "expectedReturn": 6, "risk": 1 },
    { "name": "Lumber", "expectedReturn": 12, "risk": 4 },
    { "name": "Uranium", "expectedReturn": 11, "risk": 3 },
    { "name": "Cobalt", "expectedReturn": 10, "risk": 3 },
    { "name": "Lithium", "expectedReturn": 13, "risk": 4 },
    { "name": "Propane", "expectedReturn": 9, "risk": 3 },
    { "name": "Heating Oil", "expectedReturn": 10, "risk": 3 },
    { "name": "Steel", "expectedReturn": 8, "risk": 2 }
];


const stocks = [
    { "name": "Reliance Industries", "expectedReturn": 6, "risk": 2 },
    { "name": "Tata Consultancy Services", "expectedReturn": 8, "risk": 5 },
    { "name": "Infosys", "expectedReturn": 11, "risk": 7 },
    { "name": "HDFC Bank", "expectedReturn": 14, "risk": 3 },
    { "name": "ICICI Bank", "expectedReturn": 7, "risk": 7 },
    { "name": "Kotak Mahindra Bank", "expectedReturn": 9, "risk": 7 },
    { "name": "State Bank of India", "expectedReturn": 8, "risk": 8 },
    { "name": "Bharti Airtel", "expectedReturn": 12, "risk": 4 },
    { "name": "Hindustan Unilever", "expectedReturn": 6, "risk": 6 },
    { "name": "ITC", "expectedReturn": 7, "risk": 8 },
    { "name": "Larsen & Toubro", "expectedReturn": 10, "risk": 8 },
    { "name": "Asian Paints", "expectedReturn": 12, "risk": 5 },
    { "name": "Bajaj Finance", "expectedReturn": 13, "risk": 7 },
    { "name": "Maruti Suzuki", "expectedReturn": 9, "risk": 3 },
    { "name": "Axis Bank", "expectedReturn": 11, "risk": 2 },
    { "name": "Nestle India", "expectedReturn": 6, "risk": 20 },
    { "name": "Power Grid Corporation", "expectedReturn": 5, "risk": 4 },
    { "name": "UltraTech Cement", "expectedReturn": 8, "risk": 6 },
    { "name": "Tata Steel", "expectedReturn": 10, "risk": 5 },
    { "name": "Wipro", "expectedReturn": 6, "risk": 6 },
    { "name": "HCL Technologies", "expectedReturn": 8, "risk": 10 },
    { "name": "Adani Green Energy", "expectedReturn": 17, "risk": 15 },
    { "name": "Tata Motors", "expectedReturn": 15, "risk": 2 },
    { "name": "Tech Mahindra", "expectedReturn": 7, "risk": 7 },
    { "name": "Grasim Industries", "expectedReturn": 9, "risk": 6 },
    { "name": "Bajaj Auto", "expectedReturn": 10, "risk": 11 },
    { "name": "Sun Pharmaceutical", "expectedReturn": 8, "risk": 5 },
    { "name": "Tata Power", "expectedReturn": 12, "risk": 6 },
    { "name": "Titan Company", "expectedReturn": 14, "risk": 13 },
    { "name": "Britannia Industries", "expectedReturn": 8, "risk": 7 },
    { "name": "Mahindra & Mahindra", "expectedReturn": 10, "risk": 6 },
    { "name": "Eicher Motors", "expectedReturn": 14, "risk": 15 },
    { "name": "IndusInd Bank", "expectedReturn": 12, "risk": 20 },
    { "name": "Coal India", "expectedReturn": 8, "risk": 15 },
    { "name": "Hindalco Industries", "expectedReturn": 13, "risk": 22 },
    { "name": "Hero MotoCorp", "expectedReturn": 9, "risk": 4 },
    { "name": "JSW Steel", "expectedReturn": 14, "risk": 9 },
    { "name": "GAIL India", "expectedReturn": 8, "risk": 2 },
    { "name": "Indian Oil Corporation", "expectedReturn": 7, "risk": 5 },
    { "name": "Dr. Reddy's Laboratories", "expectedReturn": 9, "risk": 4 },
    { "name": "Apollo Hospitals", "expectedReturn": 12, "risk": 7 }
];

export { commodities, stocks, cryptocurrencies };